// ============================================================
// Offline license verification.
//
// This file only ever holds the PUBLIC key — it can check that a code
// is genuine, but it cannot create new ones. Codes are generated by the
// separate `license-admin` tool, which holds the PRIVATE key and never
// ships inside this app.
//
// A code looks like:  DPL1.<payload-base64url>.<signature-base64url>
// where payload = { shopId, shopName, plan, issuedAt, expiresAt }
//
// Verification is 100% local — no network call, ever. The app checks the
// code's signature (proves it was really issued by the license-admin
// tool and hasn't been tampered with) and compares expiresAt against the
// system clock.
// ============================================================

const crypto = require('crypto');
const Store = require('electron-store');
const db = require('./db.cjs');

// ── Device-limit check-in (see license-admin/supabase/schema.sql) ─────────
// Same values as VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY in the
// web build's .env — keep both in sync if you ever rotate/replace the
// Supabase project. Leaving these blank disables device-limit enforcement
// AND cross-device data continuity (activation works exactly like before
// either feature existed).
const SUPABASE_URL = 'https://xvsafbyctlclqqybqaio.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_ClIpkWOzhUYlXUxbKcQ4zg_rVIchwBI';
const DEFAULT_DEVICE_LIMIT = 2;
const TRIAL_DAYS = 7;

// Safe to keep in the shipped app — verifying a signature does not let
// anyone forge one. Replace this with the contents of license-admin's
// public.txt after you run generate-keys.cjs.
const PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEATqyRJOdCvdqI2tnKGC8E29tWjOF82sf8DmkYaIsv5aI=
-----END PUBLIC KEY-----
`;

const publicKey = crypto.createPublicKey(PUBLIC_KEY_PEM);

// Stored separately from the SQLite database (like the PIN lock) so that
// resetting or restoring the database never touches the license.
const licenseStore = new Store({ name: 'license', encryptionKey: 'deynpro-license-v1' });

function getDeviceId() {
  let id = licenseStore.get('deviceId');
  if (!id) {
    id = crypto.randomUUID();
    licenseStore.set('deviceId', id);
  }
  return id;
}

function getDeviceLabel() {
  return `Desktop (${process.platform})`;
}

async function registerDevice(shopId, deviceId, deviceLabel, limit) {
  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    // Not configured — no enforcement, same as before this feature existed.
    return { ok: true, newDevice: true };
  }
  try {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/register_device`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        apikey: SUPABASE_ANON_KEY,
        Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
      },
      body: JSON.stringify({
        p_shop_id: shopId,
        p_device_id: deviceId,
        p_device_label: deviceLabel,
        p_limit: limit,
      }),
    });
    if (!res.ok) return { ok: false, error: `device_check_failed: ${res.status}` };
    return await res.json();
  } catch {
    // Offline right now — fail open rather than lock out a paying shop;
    // this only ever runs once per new device anyway.
    return { ok: true, newDevice: false, error: 'offline_skip_check' };
  }
}

async function checkShopStatus(shopId) {
  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) return { revoked: false };
  try {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/check_shop_status`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        apikey: SUPABASE_ANON_KEY,
        Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
      },
      body: JSON.stringify({ p_shop_id: shopId }),
    });
    if (!res.ok) return { revoked: false };
    const data = await res.json();
    return { revoked: !!data?.revoked };
  } catch {
    // Offline — fail OPEN, same reasoning as registerDevice above.
    return { revoked: false };
  }
}

// ── Cross-device data continuity ("continue on this device?") ─────────────
// Mirrors src/lib/cloudSnapshot.ts on the web build — same RPCs, same rule
// (only a device_id already registered for that shop_id may push/pull, see
// license-admin/supabase/schema.sql). Last-write-wins, not live sync: this
// just lets a newly-activated device offer to pick up an existing shop's
// data instead of starting empty.

async function callSnapshotRpc(fn, body) {
  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) return { ok: false, error: 'not_configured' };
  try {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/${fn}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        apikey: SUPABASE_ANON_KEY,
        Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
      },
      body: JSON.stringify(body),
    });
    if (!res.ok) return { ok: false, error: `rpc_failed_${res.status}` };
    return await res.json();
  } catch {
    return { ok: false, error: 'offline' };
  }
}

function countRecords(data) {
  return Object.values(data || {}).reduce((sum, rows) => {
    if (!Array.isArray(rows)) return sum;
    return sum + rows.filter((r) => !r?.deleted_at).length;
  }, 0);
}

function isLocalDataEmpty() {
  try {
    const exported = db.exportAll();
    return countRecords(exported.data) === 0;
  } catch {
    return false;
  }
}

function rowTimestamp(row) {
  const t = row?.updated_at || row?.created_at;
  const ms = t ? new Date(t).getTime() : 0;
  return Number.isFinite(ms) ? ms : 0;
}

/**
 * Merges two exportAll()-shaped data objects, table by table, record by
 * record — mirrors src/lib/cloudSnapshot.ts's mergeSnapshotData() on the
 * web build exactly. A record present on only one side is always kept; a
 * record present on both sides keeps whichever has the newer updated_at
 * (ties go to local). This is what makes syncing safe with any number of
 * devices active at once — nobody's push can silently erase what another
 * device added since its own last sync.
 */
function mergeSnapshotData(localData, remoteData) {
  const tables = new Set([...Object.keys(localData || {}), ...Object.keys(remoteData || {})]);
  const merged = {};

  for (const table of tables) {
    const localRows = Array.isArray(localData?.[table]) ? localData[table] : [];
    const remoteRows = Array.isArray(remoteData?.[table]) ? remoteData[table] : [];

    const byId = new Map();
    for (const row of remoteRows) {
      if (row && row.id != null) byId.set(row.id, row);
    }
    for (const row of localRows) {
      if (!row || row.id == null) continue;
      const existing = byId.get(row.id);
      if (!existing || rowTimestamp(row) >= rowTimestamp(existing)) {
        byId.set(row.id, row);
      }
    }
    merged[table] = Array.from(byId.values());
  }

  return merged;
}

// "Start fresh" opt-out — see the matching comment in
// src/lib/cloudSnapshot.ts. Stored in licenseStore (electron-store) so it
// survives restarts, same as the license code and device id.
function optOutOfPull(shopId) {
  const optedOut = licenseStore.get('noPullShopIds') || [];
  if (!optedOut.includes(shopId)) {
    optedOut.push(shopId);
    licenseStore.set('noPullShopIds', optedOut);
  }
}

function hasOptedOutOfPull(shopId) {
  const optedOut = licenseStore.get('noPullShopIds') || [];
  return optedOut.includes(shopId);
}

async function checkSnapshotMeta(shopId, deviceId) {
  const result = await callSnapshotRpc('get_shop_snapshot_meta', { p_shop_id: shopId, p_device_id: deviceId });
  if (!result?.ok) return null;
  return { exists: !!result.exists, updatedAt: result.updated_at, recordCount: result.record_count };
}

/** Metadata-only check for the current shop's cloud snapshot — used to show
 * "last synced" info in Settings without downloading the full data. */
async function checkSnapshotForCurrentShop() {
  const status = await getStatus();
  if (!status.activated || !status.shopId) return null;
  return checkSnapshotMeta(status.shopId, getDeviceId());
}

/**
 * The one real operation: fetch the cloud snapshot, merge with local data,
 * push the merged result up, and (unless this device opted out via
 * startFreshSnapshot) bring this device's local database up to the
 * merged state too.
 */
async function reconcile(shopId, { skipLocalImport = false } = {}) {
  const deviceId = getDeviceId();

  const remoteResult = await callSnapshotRpc('get_shop_snapshot', { p_shop_id: shopId, p_device_id: deviceId });
  if (!remoteResult?.ok) {
    return { ok: false, error: remoteResult?.error === 'offline' ? 'offline' : (remoteResult?.error || 'Could not reach the server — check your connection and try again.') };
  }
  const remoteData = remoteResult.exists ? remoteResult.data : {};

  const exported = db.exportAll();
  const merged = mergeSnapshotData(exported.data, remoteData);
  const recordCount = countRecords(merged);

  const pushResult = await callSnapshotRpc('push_shop_snapshot', {
    p_shop_id: shopId,
    p_device_id: deviceId,
    p_data: merged,
    p_record_count: recordCount,
  });
  if (!pushResult?.ok) {
    return { ok: false, error: pushResult?.error === 'offline' ? 'offline' : 'Could not sync to the cloud right now.' };
  }

  if (!skipLocalImport) {
    db.importAll({ data: merged });
  }

  return { ok: true, recordCount };
}

/** Downloads the current shop's cloud snapshot into this device's local SQLite database
 * — called right after activation when the user picks "continue with existing data",
 * so this always imports (the device is fresh at that point). */
async function pullSnapshot() {
  const status = await getStatus();
  if (!status.activated || !status.shopId) return { ok: false, error: 'Not activated.' };
  return reconcile(status.shopId, { skipLocalImport: false });
}

/** A full two-way reconcile — called periodically in the background and by
 * the manual "Sync now" button, respecting this device's "start fresh"
 * opt-out if it set one. */
async function pushSnapshot() {
  const status = await getStatus();
  if (!status.activated || !status.shopId) return { ok: false, error: 'Not activated.' };
  return reconcile(status.shopId, { skipLocalImport: hasOptedOutOfPull(status.shopId) });
}

/** Called when the user picks "start fresh on this device" instead of
 * bringing in the shop's existing cloud data. This device keeps
 * contributing its own new data upward, but stops automatically pulling
 * other devices' data back into itself. */
function startFreshSnapshot() {
  const status_ = licenseStore.get('code');
  if (!status_) return;
  const result = parseAndVerify(status_);
  if (result.valid && result.payload?.shopId) optOutOfPull(result.payload.shopId);
}

function b64urlToBuf(s) {
  s = s.replace(/-/g, '+').replace(/_/g, '/');
  while (s.length % 4) s += '=';
  return Buffer.from(s, 'base64');
}

function parseAndVerifyRaw(code) {
  if (!code || typeof code !== 'string') return { valid: false, error: 'No code provided.' };
  const parts = code.trim().split('.');
  if (parts.length !== 3) {
    return { valid: false, error: 'This does not look like a valid code.' };
  }
  const [prefix, payloadB64, sigB64] = parts;

  let ok = false;
  try {
    ok = crypto.verify(null, Buffer.from(payloadB64), publicKey, b64urlToBuf(sigB64));
  } catch {
    return { valid: false, error: 'Could not read this code — please check it was copied in full.' };
  }
  if (!ok) return { valid: false, error: 'This code is not genuine, or has been altered.' };

  let payload;
  try {
    payload = JSON.parse(b64urlToBuf(payloadB64).toString('utf8'));
  } catch {
    return { valid: false, error: 'Could not read this code — please check it was copied in full.' };
  }
  return { valid: true, prefix, payload };
}

function parseAndVerify(code) {
  const result = parseAndVerifyRaw(code);
  if (!result.valid) return result;
  if (result.prefix !== 'DPL1') return { valid: false, error: 'This is not a license code.' };
  if (!result.payload.shopId || !result.payload.expiresAt) {
    return { valid: false, error: 'This code is missing required information.' };
  }
  return result;
}

async function registerTrialDevice(deviceId, deviceLabel, trialExpiresAt, force) {
  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) return;
  if (!force) {
    const lastPing = licenseStore.get('trialLastPing') || 0;
    if (Date.now() - lastPing < 24 * 60 * 60 * 1000) return; // once a day is plenty
  }
  try {
    await fetch(`${SUPABASE_URL}/rest/v1/rpc/register_trial_device`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        apikey: SUPABASE_ANON_KEY,
        Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
      },
      body: JSON.stringify({
        p_device_id: deviceId,
        p_device_label: deviceLabel,
        p_trial_expires_at: new Date(trialExpiresAt).toISOString(),
      }),
    });
    licenseStore.set('trialLastPing', Date.now());
  } catch {
    // Offline — just try again next time. Never blocks the trial.
  }
}

function getTrialStatus() {
  let start = licenseStore.get('trialStart');
  const isNewTrial = !start;
  if (!start) {
    start = Date.now();
    licenseStore.set('trialStart', start);
  }
  const expiresAt = start + TRIAL_DAYS * 24 * 60 * 60 * 1000;
  const trialDaysLeft = Math.max(0, Math.ceil((expiresAt - Date.now()) / (24 * 60 * 60 * 1000)));

  // Best-effort, fire-and-forget — see registerTrialDevice above. Purely
  // so license-admin can see this trial exists; never blocks anything.
  registerTrialDevice(getDeviceId(), getDeviceLabel(), expiresAt, isNewTrial).catch(() => {});

  return { expiresAt, expired: Date.now() > expiresAt, trialDaysLeft };
}

/** Sync, no network — just reads whatever shopId (if any) is in the locally
 * stored code, for use at app startup before the async getStatus() below
 * has a chance to run (see main.cjs's db.init call). */
function getStoredShopId() {
  const code = licenseStore.get('code');
  if (!code) return null;
  const result = parseAndVerify(code);
  return result.valid ? result.payload.shopId : null;
}

/** Returns the current activation status: local signature+expiry check,
 * falling back to the free trial if no code was ever entered, plus an
 * online-only remote-deactivation check (fails open when offline). */
async function getStatus() {
  const code = licenseStore.get('code');

  if (!code) {
    const trial = getTrialStatus();
    if (!trial.expired) {
      return { activated: true, trial: true, trialDaysLeft: trial.trialDaysLeft, expiresAt: trial.expiresAt };
    }
    return { activated: false, trialExpired: true };
  }

  const result = parseAndVerify(code);
  if (!result.valid) return { activated: false, error: result.error };

  const { payload } = result;
  const expired = Date.now() > payload.expiresAt;

  if (!expired) {
    const { revoked } = await checkShopStatus(payload.shopId);
    if (revoked) {
      return {
        activated: false,
        revoked: true,
        shopId: payload.shopId,
        shopName: payload.shopName,
        error: 'Access to this code has been turned off. Contact support if you think this is a mistake.',
      };
    }
  }

  return {
    activated: true,
    expired,
    shopId: payload.shopId,
    shopName: payload.shopName,
    plan: payload.plan,
    issuedAt: payload.issuedAt,
    expiresAt: payload.expiresAt,
  };
}

/** Verifies and stores a newly pasted code. */
async function activate(code) {
  const result = parseAndVerify(code);
  if (!result.valid) return { ok: false, error: result.error };

  if (Date.now() > result.payload.expiresAt) {
    return { ok: false, error: 'This code has already expired — ask for a new one.' };
  }

  // A shop that's been remotely deactivated shouldn't be able to activate
  // on a brand new device either, not just get caught on a recheck later.
  const { revoked } = await checkShopStatus(result.payload.shopId);
  if (revoked) {
    return { ok: false, error: 'Access to this code has been turned off. Contact support if you think this is a mistake.' };
  }

  const deviceId = getDeviceId();
  const deviceLabel = getDeviceLabel();
  const limit = result.payload.deviceLimit || DEFAULT_DEVICE_LIMIT;
  const deviceResult = await registerDevice(result.payload.shopId, deviceId, deviceLabel, limit);

  if (!deviceResult.ok) {
    if (deviceResult.error === 'device_limit_reached') {
      return {
        ok: false,
        error: `This code is already active on ${deviceResult.limit ?? limit} device(s) — the maximum for this subscription. Ask support to free up a device slot.`,
        deviceLimitReached: true,
        deviceCount: deviceResult.count,
        deviceLimit: deviceResult.limit ?? limit,
      };
    }
    return { ok: false, error: 'Could not verify this code right now — check your connection and try again.' };
  }

  licenseStore.set('code', code.trim());

  // Switch to (or create) THIS shop's own database file before touching
  // any data below — critical so a device that previously belonged to a
  // different shop (or had none activated yet) never reads or writes that
  // other shop's data under this shop's license. See electron/db.cjs.
  db.init(result.payload.shopId);

  // Only offer to "continue with existing data" when this device is
  // genuinely fresh — never overwrite a device that already has its own
  // real data just because it happens to (re-)activate the same code.
  let snapshotAvailable;
  try {
    if (isLocalDataEmpty()) {
      const meta = await checkSnapshotMeta(result.payload.shopId, deviceId);
      if (meta?.exists) {
        snapshotAvailable = { updatedAt: meta.updatedAt, recordCount: meta.recordCount };
      }
    }
  } catch {
    // Best-effort only — a failed check just means no prompt is shown.
  }

  return { ok: true, ...(await getStatus()), snapshotAvailable };
}

/** Support/testing use only — removes the stored code. */
function clear() {
  licenseStore.delete('code');
  // Switch back to the neutral placeholder database so nothing from the
  // previous shop stays reachable while this device is unactivated.
  try { db.init(null); } catch (_) {}
  return { ok: true };
}

module.exports = { getStatus, getStoredShopId, activate, clear, verifyRawCode: parseAndVerifyRaw, pullSnapshot, pushSnapshot, checkSnapshot: checkSnapshotForCurrentShop, startFreshSnapshot };
