// ============================================================
// Offline license verification.
//
// This file only ever holds the PUBLIC key — it can check that a code
// is genuine, but it cannot create new ones. Codes are generated by the
// separate `license-admin` tool, which holds the PRIVATE key and never
// ships inside this app.
//
// A code looks like:  DPL1.<payload-base64url>.<signature-base64url>
// where payload = { shopId, shopName, plan, issuedAt, expiresAt }
//
// Verification is 100% local — no network call, ever. The app checks the
// code's signature (proves it was really issued by the license-admin
// tool and hasn't been tampered with) and compares expiresAt against the
// system clock.
// ============================================================

const crypto = require('crypto');
const Store = require('electron-store');
const db = require('./db.cjs');

// ── Device-limit check-in (see license-admin/supabase/schema.sql) ─────────
// Same values as VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY in the
// web build's .env — keep both in sync if you ever rotate/replace the
// Supabase project. Leaving these blank disables device-limit enforcement
// AND cross-device data continuity (activation works exactly like before
// either feature existed).
const SUPABASE_URL = 'https://xvsafbyctlclqqybqaio.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_ClIpkWOzhUYlXUxbKcQ4zg_rVIchwBI';
const DEFAULT_DEVICE_LIMIT = 2;

// Safe to keep in the shipped app — verifying a signature does not let
// anyone forge one. Replace this with the contents of license-admin's
// public.txt after you run generate-keys.cjs.
const PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEATqyRJOdCvdqI2tnKGC8E29tWjOF82sf8DmkYaIsv5aI=
-----END PUBLIC KEY-----
`;

const publicKey = crypto.createPublicKey(PUBLIC_KEY_PEM);

// Stored separately from the SQLite database (like the PIN lock) so that
// resetting or restoring the database never touches the license.
const licenseStore = new Store({ name: 'license', encryptionKey: 'deynpro-license-v1' });

function getDeviceId() {
  let id = licenseStore.get('deviceId');
  if (!id) {
    id = crypto.randomUUID();
    licenseStore.set('deviceId', id);
  }
  return id;
}

function getDeviceLabel() {
  return `Desktop (${process.platform})`;
}

async function registerDevice(shopId, deviceId, deviceLabel, limit) {
  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    // Not configured — no enforcement, same as before this feature existed.
    return { ok: true, newDevice: true };
  }
  try {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/register_device`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        apikey: SUPABASE_ANON_KEY,
        Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
      },
      body: JSON.stringify({
        p_shop_id: shopId,
        p_device_id: deviceId,
        p_device_label: deviceLabel,
        p_limit: limit,
      }),
    });
    if (!res.ok) return { ok: false, error: `device_check_failed: ${res.status}` };
    return await res.json();
  } catch {
    // Offline right now — fail open rather than lock out a paying shop;
    // this only ever runs once per new device anyway.
    return { ok: true, newDevice: false, error: 'offline_skip_check' };
  }
}

// ── Cross-device data continuity ("continue on this device?") ─────────────
// Mirrors src/lib/cloudSnapshot.ts on the web build — same RPCs, same rule
// (only a device_id already registered for that shop_id may push/pull, see
// license-admin/supabase/schema.sql). Last-write-wins, not live sync: this
// just lets a newly-activated device offer to pick up an existing shop's
// data instead of starting empty.

async function callSnapshotRpc(fn, body) {
  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) return { ok: false, error: 'not_configured' };
  try {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/${fn}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        apikey: SUPABASE_ANON_KEY,
        Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
      },
      body: JSON.stringify(body),
    });
    if (!res.ok) return { ok: false, error: `rpc_failed_${res.status}` };
    return await res.json();
  } catch {
    return { ok: false, error: 'offline' };
  }
}

function countRecords(data) {
  return Object.values(data || {}).reduce((sum, rows) => {
    if (!Array.isArray(rows)) return sum;
    return sum + rows.filter((r) => !r?.deleted_at).length;
  }, 0);
}

function isLocalDataEmpty() {
  try {
    const exported = db.exportAll();
    return countRecords(exported.data) === 0;
  } catch {
    return false;
  }
}

async function checkSnapshotMeta(shopId, deviceId) {
  const result = await callSnapshotRpc('get_shop_snapshot_meta', { p_shop_id: shopId, p_device_id: deviceId });
  if (!result?.ok) return null;
  return { exists: !!result.exists, updatedAt: result.updated_at, recordCount: result.record_count };
}

/** Metadata-only check for the current shop's cloud snapshot — used to show
 * "last synced" info in Settings without downloading the full data. */
async function checkSnapshotForCurrentShop() {
  const status = getStatus();
  if (!status.activated || !status.shopId) return null;
  return checkSnapshotMeta(status.shopId, getDeviceId());
}

/** Downloads the current shop's cloud snapshot into this device's local SQLite database. */
async function pullSnapshot() {
  const status = getStatus();
  if (!status.activated || !status.shopId) return { ok: false, error: 'Not activated.' };
  const deviceId = getDeviceId();
  const result = await callSnapshotRpc('get_shop_snapshot', { p_shop_id: status.shopId, p_device_id: deviceId });
  if (!result?.ok) return { ok: false, error: 'Could not reach the server — check your connection and try again.' };
  if (!result.exists || !result.data) return { ok: false, error: 'No cloud data was found for this shop.' };
  db.importAll({ data: result.data });
  return { ok: true };
}

/** Uploads this device's local SQLite database as the shop's latest cloud snapshot. */
async function pushSnapshot() {
  const status = getStatus();
  if (!status.activated || !status.shopId) return { ok: false, error: 'Not activated.' };
  const deviceId = getDeviceId();
  const exported = db.exportAll();
  const result = await callSnapshotRpc('push_shop_snapshot', {
    p_shop_id: status.shopId,
    p_device_id: deviceId,
    p_data: exported.data,
    p_record_count: countRecords(exported.data),
  });
  if (!result?.ok) return { ok: false, error: result?.error === 'offline' ? 'offline' : 'Could not sync to the cloud right now.' };
  return { ok: true };
}

function b64urlToBuf(s) {
  s = s.replace(/-/g, '+').replace(/_/g, '/');
  while (s.length % 4) s += '=';
  return Buffer.from(s, 'base64');
}

function parseAndVerifyRaw(code) {
  if (!code || typeof code !== 'string') return { valid: false, error: 'No code provided.' };
  const parts = code.trim().split('.');
  if (parts.length !== 3) {
    return { valid: false, error: 'This does not look like a valid code.' };
  }
  const [prefix, payloadB64, sigB64] = parts;

  let ok = false;
  try {
    ok = crypto.verify(null, Buffer.from(payloadB64), publicKey, b64urlToBuf(sigB64));
  } catch {
    return { valid: false, error: 'Could not read this code — please check it was copied in full.' };
  }
  if (!ok) return { valid: false, error: 'This code is not genuine, or has been altered.' };

  let payload;
  try {
    payload = JSON.parse(b64urlToBuf(payloadB64).toString('utf8'));
  } catch {
    return { valid: false, error: 'Could not read this code — please check it was copied in full.' };
  }
  return { valid: true, prefix, payload };
}

function parseAndVerify(code) {
  const result = parseAndVerifyRaw(code);
  if (!result.valid) return result;
  if (result.prefix !== 'DPL1') return { valid: false, error: 'This is not a license code.' };
  if (!result.payload.shopId || !result.payload.expiresAt) {
    return { valid: false, error: 'This code is missing required information.' };
  }
  return result;
}

/** Returns the current activation status, purely from the locally stored code + system clock. */
function getStatus() {
  const code = licenseStore.get('code');
  if (!code) return { activated: false };

  const result = parseAndVerify(code);
  if (!result.valid) return { activated: false, error: result.error };

  const { payload } = result;
  const expired = Date.now() > payload.expiresAt;

  return {
    activated: true,
    expired,
    shopId: payload.shopId,
    shopName: payload.shopName,
    plan: payload.plan,
    issuedAt: payload.issuedAt,
    expiresAt: payload.expiresAt,
  };
}

/** Verifies and stores a newly pasted code. */
async function activate(code) {
  const result = parseAndVerify(code);
  if (!result.valid) return { ok: false, error: result.error };

  if (Date.now() > result.payload.expiresAt) {
    return { ok: false, error: 'This code has already expired — ask for a new one.' };
  }

  const deviceId = getDeviceId();
  const deviceLabel = getDeviceLabel();
  const limit = result.payload.deviceLimit || DEFAULT_DEVICE_LIMIT;
  const deviceResult = await registerDevice(result.payload.shopId, deviceId, deviceLabel, limit);

  if (!deviceResult.ok) {
    if (deviceResult.error === 'device_limit_reached') {
      return {
        ok: false,
        error: `This code is already active on ${deviceResult.limit ?? limit} device(s) — the maximum for this subscription. Ask support to free up a device slot.`,
        deviceLimitReached: true,
        deviceCount: deviceResult.count,
        deviceLimit: deviceResult.limit ?? limit,
      };
    }
    return { ok: false, error: 'Could not verify this code right now — check your connection and try again.' };
  }

  licenseStore.set('code', code.trim());

  // Switch to (or create) THIS shop's own database file before touching
  // any data below — critical so a device that previously belonged to a
  // different shop (or had none activated yet) never reads or writes that
  // other shop's data under this shop's license. See electron/db.cjs.
  db.init(result.payload.shopId);

  // Only offer to "continue with existing data" when this device is
  // genuinely fresh — never overwrite a device that already has its own
  // real data just because it happens to (re-)activate the same code.
  let snapshotAvailable;
  try {
    if (isLocalDataEmpty()) {
      const meta = await checkSnapshotMeta(result.payload.shopId, deviceId);
      if (meta?.exists) {
        snapshotAvailable = { updatedAt: meta.updatedAt, recordCount: meta.recordCount };
      }
    }
  } catch {
    // Best-effort only — a failed check just means no prompt is shown.
  }

  return { ok: true, ...getStatus(), snapshotAvailable };
}

/** Support/testing use only — removes the stored code. */
function clear() {
  licenseStore.delete('code');
  // Switch back to the neutral placeholder database so nothing from the
  // previous shop stays reachable while this device is unactivated.
  try { db.init(null); } catch (_) {}
  return { ok: true };
}

module.exports = { getStatus, activate, clear, verifyRawCode: parseAndVerifyRaw, pullSnapshot, pushSnapshot, checkSnapshot: checkSnapshotForCurrentShop };
