// ============================================================
// Offline license verification.
//
// This file only ever holds the PUBLIC key — it can check that a code
// is genuine, but it cannot create new ones. Codes are generated by the
// separate `license-admin` tool, which holds the PRIVATE key and never
// ships inside this app.
//
// A code looks like:  DPL1.<payload-base64url>.<signature-base64url>
// where payload = { shopId, shopName, plan, issuedAt, expiresAt }
//
// Verification is 100% local — no network call, ever. The app checks the
// code's signature (proves it was really issued by the license-admin
// tool and hasn't been tampered with) and compares expiresAt against the
// system clock.
// ============================================================

const crypto = require('crypto');
const Store = require('electron-store');

// ── Device-limit check-in (see license-admin/supabase/schema.sql) ─────────
// Fill these in after you set up Supabase (see README) — same values as
// VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY used by the web build. Leaving
// them blank disables device-limit enforcement (activation works exactly
// like before this feature existed).
const SUPABASE_URL = '';
const SUPABASE_ANON_KEY = '';
const DEFAULT_DEVICE_LIMIT = 2;

// Safe to keep in the shipped app — verifying a signature does not let
// anyone forge one. Replace this with the contents of license-admin's
// public.txt after you run generate-keys.cjs.
const PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEATqyRJOdCvdqI2tnKGC8E29tWjOF82sf8DmkYaIsv5aI=
-----END PUBLIC KEY-----
`;

const publicKey = crypto.createPublicKey(PUBLIC_KEY_PEM);

// Stored separately from the SQLite database (like the PIN lock) so that
// resetting or restoring the database never touches the license.
const licenseStore = new Store({ name: 'license', encryptionKey: 'deynpro-license-v1' });

function getDeviceId() {
  let id = licenseStore.get('deviceId');
  if (!id) {
    id = crypto.randomUUID();
    licenseStore.set('deviceId', id);
  }
  return id;
}

function getDeviceLabel() {
  return `Desktop (${process.platform})`;
}

async function registerDevice(shopId, deviceId, deviceLabel, limit) {
  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    // Not configured — no enforcement, same as before this feature existed.
    return { ok: true, newDevice: true };
  }
  try {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/rpc/register_device`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        apikey: SUPABASE_ANON_KEY,
        Authorization: `Bearer ${SUPABASE_ANON_KEY}`,
      },
      body: JSON.stringify({
        p_shop_id: shopId,
        p_device_id: deviceId,
        p_device_label: deviceLabel,
        p_limit: limit,
      }),
    });
    if (!res.ok) return { ok: false, error: `device_check_failed: ${res.status}` };
    return await res.json();
  } catch {
    // Offline right now — fail open rather than lock out a paying shop;
    // this only ever runs once per new device anyway.
    return { ok: true, newDevice: false, error: 'offline_skip_check' };
  }
}

function b64urlToBuf(s) {
  s = s.replace(/-/g, '+').replace(/_/g, '/');
  while (s.length % 4) s += '=';
  return Buffer.from(s, 'base64');
}

function parseAndVerifyRaw(code) {
  if (!code || typeof code !== 'string') return { valid: false, error: 'No code provided.' };
  const parts = code.trim().split('.');
  if (parts.length !== 3) {
    return { valid: false, error: 'This does not look like a valid code.' };
  }
  const [prefix, payloadB64, sigB64] = parts;

  let ok = false;
  try {
    ok = crypto.verify(null, Buffer.from(payloadB64), publicKey, b64urlToBuf(sigB64));
  } catch {
    return { valid: false, error: 'Could not read this code — please check it was copied in full.' };
  }
  if (!ok) return { valid: false, error: 'This code is not genuine, or has been altered.' };

  let payload;
  try {
    payload = JSON.parse(b64urlToBuf(payloadB64).toString('utf8'));
  } catch {
    return { valid: false, error: 'Could not read this code — please check it was copied in full.' };
  }
  return { valid: true, prefix, payload };
}

function parseAndVerify(code) {
  const result = parseAndVerifyRaw(code);
  if (!result.valid) return result;
  if (result.prefix !== 'DPL1') return { valid: false, error: 'This is not a license code.' };
  if (!result.payload.shopId || !result.payload.expiresAt) {
    return { valid: false, error: 'This code is missing required information.' };
  }
  return result;
}

/** Returns the current activation status, purely from the locally stored code + system clock. */
function getStatus() {
  const code = licenseStore.get('code');
  if (!code) return { activated: false };

  const result = parseAndVerify(code);
  if (!result.valid) return { activated: false, error: result.error };

  const { payload } = result;
  const expired = Date.now() > payload.expiresAt;

  return {
    activated: true,
    expired,
    shopId: payload.shopId,
    shopName: payload.shopName,
    plan: payload.plan,
    issuedAt: payload.issuedAt,
    expiresAt: payload.expiresAt,
  };
}

/** Verifies and stores a newly pasted code. */
async function activate(code) {
  const result = parseAndVerify(code);
  if (!result.valid) return { ok: false, error: result.error };

  if (Date.now() > result.payload.expiresAt) {
    return { ok: false, error: 'This code has already expired — ask for a new one.' };
  }

  const deviceId = getDeviceId();
  const deviceLabel = getDeviceLabel();
  const limit = result.payload.deviceLimit || DEFAULT_DEVICE_LIMIT;
  const deviceResult = await registerDevice(result.payload.shopId, deviceId, deviceLabel, limit);

  if (!deviceResult.ok) {
    if (deviceResult.error === 'device_limit_reached') {
      return {
        ok: false,
        error: `This code is already active on ${deviceResult.limit ?? limit} device(s) — the maximum for this subscription. Ask support to free up a device slot.`,
        deviceLimitReached: true,
        deviceCount: deviceResult.count,
        deviceLimit: deviceResult.limit ?? limit,
      };
    }
    return { ok: false, error: 'Could not verify this code right now — check your connection and try again.' };
  }

  licenseStore.set('code', code.trim());
  return { ok: true, ...getStatus() };
}

/** Support/testing use only — removes the stored code. */
function clear() {
  licenseStore.delete('code');
  return { ok: true };
}

module.exports = { getStatus, activate, clear, verifyRawCode: parseAndVerifyRaw };
