import { useRef } from 'react';
import { useProducts } from '@/hooks/useProducts';
import { useSuppliers } from '@/hooks/useSuppliers';
import { useShopSettings } from '@/hooks/useShopSettings';
import { useCurrencySettings, formatCurrency } from '@/hooks/useCurrencySettings';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Printer, Share2, Package, AlertTriangle, ShoppingCart } from 'lucide-react';
import { format } from 'date-fns';
import { toast } from 'sonner';

export default function ReorderList() {
  const printRef = useRef<HTMLDivElement>(null);
  const { data: products } = useProducts();
  const { data: suppliers } = useSuppliers();
  const { data: shopSettings } = useShopSettings();
  const { data: currencyData } = useCurrencySettings();
  const fmt = (n: number) => formatCurrency(n, currencyData?.base_currency || 'KES');

  // Products that are at or below their low stock threshold
  const lowStock = (products || []).filter(p => p.quantity <= p.low_stock_threshold);

  // Group by supplier
  const supplierMap: Record<string, any> = {};
  (suppliers || []).forEach(s => { supplierMap[s.id] = s; });

  const grouped: Record<string, { supplier: any; products: any[] }> = {};
  lowStock.forEach(p => {
    const key = p.supplier_id || '__none__';
    if (!grouped[key]) {
      grouped[key] = {
        supplier: p.supplier_id ? supplierMap[p.supplier_id] : null,
        products: [],
      };
    }
    grouped[key].products.push(p);
  });

  const groups = Object.values(grouped).sort((a, b) => {
    if (!a.supplier) return 1;
    if (!b.supplier) return -1;
    return (a.supplier.name || '').localeCompare(b.supplier.name || '');
  });

  const handlePrint = () => {
    const content = printRef.current;
    if (!content) return;
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(`
      <html>
        <head>
          <title>Reorder List - ${shopSettings?.shop_name || 'Shop'}</title>
          <style>
            * { box-sizing: border-box; margin: 0; padding: 0; }
            body { font-family: Arial, sans-serif; font-size: 13px; padding: 24px; color: #111; }
            h1 { font-size: 20px; font-weight: bold; margin-bottom: 4px; }
            .meta { color: #666; font-size: 12px; margin-bottom: 20px; }
            .group { margin-bottom: 20px; page-break-inside: avoid; }
            .group-title { font-size: 14px; font-weight: bold; background: #f3f4f6; padding: 6px 10px; border-radius: 4px; margin-bottom: 8px; }
            table { width: 100%; border-collapse: collapse; }
            th { text-align: left; font-size: 11px; color: #555; border-bottom: 1px solid #e5e7eb; padding: 4px 8px; }
            td { padding: 6px 8px; border-bottom: 1px solid #f3f4f6; vertical-align: middle; }
            .qty-low { color: #dc2626; font-weight: bold; }
            .qty-warn { color: #d97706; font-weight: bold; }
            .footer { margin-top: 24px; font-size: 11px; color: #999; border-top: 1px solid #e5e7eb; padding-top: 12px; }
          </style>
        </head>
        <body>
          ${content.innerHTML}
          <div class="footer">Generated by ${shopSettings?.shop_name || 'DeynPro'} · ${format(new Date(), 'PPpp')}</div>
        </body>
      </html>
    `);
    win.document.close();
    win.focus();
    win.print();
    win.close();
  };

  const handleShare = () => {
    if (!lowStock.length) return;
    const lines = [
      `🛒 *Reorder List — ${shopSettings?.shop_name || 'Shop'}*`,
      `📅 ${format(new Date(), 'PPP')}`,
      '',
      ...groups.map(g => {
        const supName = g.supplier?.name || 'No Supplier';
        const supPhone = g.supplier?.phone ? ` (${g.supplier.phone})` : '';
        const items = g.products.map(p =>
          `  • ${p.name} — Qty: ${p.quantity} (reorder at ≤${p.low_stock_threshold})`
        ).join('\n');
        return `*${supName}${supPhone}*\n${items}`;
      }),
    ];
    const text = lines.join('\n');
    if (navigator.share) {
      navigator.share({ title: 'Reorder List', text }).catch(() => {});
    } else {
      navigator.clipboard.writeText(text).then(() => toast.success('Copied to clipboard!'));
    }
  };

  return (
    <div className="space-y-4 pb-20 md:pb-0">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-foreground flex items-center gap-2">
            <ShoppingCart size={24} className="text-primary" /> Reorder List
          </h1>
          <p className="text-sm text-muted-foreground">
            {lowStock.length} product{lowStock.length !== 1 ? 's' : ''} need restocking
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" className="gap-2" onClick={handleShare} disabled={!lowStock.length}>
            <Share2 size={16} /> Share
          </Button>
          <Button className="gradient-primary border-0 gap-2" onClick={handlePrint} disabled={!lowStock.length}>
            <Printer size={16} /> Print
          </Button>
        </div>
      </div>

      {lowStock.length === 0 && (
        <Card className="shadow-card">
          <CardContent className="py-16 text-center">
            <Package size={48} className="mx-auto text-muted-foreground/30 mb-3" />
            <p className="text-muted-foreground font-medium">All products are well stocked!</p>
            <p className="text-sm text-muted-foreground mt-1">Nothing needs reordering right now.</p>
          </CardContent>
        </Card>
      )}

      {/* Printable content */}
      <div ref={printRef}>
        {/* Print header (hidden on screen) */}
        <div className="hidden">
          <h1>{shopSettings?.shop_name || 'Shop'} — Reorder List</h1>
          <p className="meta">Generated: {format(new Date(), 'PPpp')}</p>
        </div>

        <div className="space-y-4">
          {groups.map((group, gi) => (
            <Card key={gi} className="shadow-card overflow-hidden">
              <CardHeader className="pb-2 bg-muted/30">
                <CardTitle className="text-sm font-semibold flex items-center gap-2">
                  {group.supplier ? (
                    <>
                      <Package size={15} className="text-primary" />
                      <span>{group.supplier.name}</span>
                      {group.supplier.phone && (
                        <Badge variant="outline" className="text-xs font-normal ml-1">
                          {group.supplier.phone}
                        </Badge>
                      )}
                      {group.supplier.email && (
                        <Badge variant="outline" className="text-xs font-normal">
                          {group.supplier.email}
                        </Badge>
                      )}
                    </>
                  ) : (
                    <>
                      <AlertTriangle size={15} className="text-warning" />
                      <span className="text-muted-foreground">No Supplier Assigned</span>
                    </>
                  )}
                </CardTitle>
              </CardHeader>
              <CardContent className="p-0">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-border">
                      <th className="text-left text-xs text-muted-foreground font-medium px-4 py-2">Product</th>
                      <th className="text-center text-xs text-muted-foreground font-medium px-4 py-2">Current Qty</th>
                      <th className="text-center text-xs text-muted-foreground font-medium px-4 py-2">Alert At</th>
                      <th className="text-right text-xs text-muted-foreground font-medium px-4 py-2">Cost Price</th>
                      <th className="text-left text-xs text-muted-foreground font-medium px-4 py-2">Category</th>
                    </tr>
                  </thead>
                  <tbody>
                    {group.products.map((p, i) => (
                      <tr key={p.id} className={`border-b border-border last:border-0 ${i % 2 === 0 ? '' : 'bg-muted/20'}`}>
                        <td className="px-4 py-3 font-medium text-card-foreground">{p.name}</td>
                        <td className="px-4 py-3 text-center">
                          <span className={`font-bold ${p.quantity === 0 ? 'text-destructive' : 'text-warning'}`}>
                            {p.quantity === 0 ? '⚠ OUT' : p.quantity}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-center text-muted-foreground">{p.low_stock_threshold}</td>
                        <td className="px-4 py-3 text-right text-muted-foreground">{fmt(p.cost_price)}</td>
                        <td className="px-4 py-3 text-muted-foreground">{p.category || '—'}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      {lowStock.length > 0 && (
        <p className="text-xs text-muted-foreground text-center pt-2">
          Tip: Set a supplier on each product in Products → Edit to group this list by supplier contact.
        </p>
      )}
    </div>
  );
}
